CREATE TABLE NORMAL_ACCOUNT(
	NAME VARCHAR(30),
	EMAIL VARCHAR(30),
	PASSWD VARCHAR(20),
	PRIMARY KEY(EMAIL)
);

CREATE TABLE RENTER_ACCOUNT(
	NAME VARCHAR(30),
	EMAIL VARCHAR(30),
	PASSWD VARCHAR(20),
	PRIMARY KEY(EMAIL)
);

CREATE TABLE ESTATE(
	REGINUM INT(9) AUTO_INCREMENT,
	NAME VARCHAR(30),
	PRICE INT(10),
	ADDRESS VARCHAR(60),
	AREA INT(4),
	HOUSEDONG VARCHAR(6),
	HOUSESTAIR VARCHAR(6),
	POSSIBLEDATE DATE,
	DIRECTION VARCHAR(3),
	PHONENUM VARCHAR(12),
	PRIMARY KEY(REGINUM)
);

CREATE TABLE CONTRACTADDR(
	EMAIL VARCHAR(30),
	ADDR VARCHAR(512),
	PRIMARY KEY(ADDR)
);